export const metaConfig = {
  dataview: "PL_MDVIEW_004",
  serverUrl: "http://dev.veritech.mn:8080/erp-services/RestWS/runJson",
  fileAttach: "http://dev.veritech.mn:8080/erp-services/FileServlet",
  imageUrl: "https://dev.veritech.mn/",
  METATYPE_METAGROUP: "200101010000016",
  METATYPE_BUSINESSPROCESS: "200101010000011",
  COMMAND_DATAVIEW: "PL_MDVIEW_004",
  COMMAND_LAYOUT: "layoutHdr_004",
  metaDev: {
    serverUrl: "http://dev.veritech.mn:8080/erp-services/RestWS/runJson",
    fileAttach: "http://dev.veritech.mn:8080/erp-services/FileServlet",
    thisis: "Энэ бол DEV юм шүү.",
    username: "ariunbuyan.t",
    password: "123",
    metaName: "metaDev",
    imageRootURL: "https://dev.veritech.mn/",
  },
  metaCloud: {
    serverUrl: "https://cloud.veritech.mn:8181/erp-services/RestWS/runJson",
    fileAttach: "https://cloud.veritech.mn:8181/erp-services/FileServlet",
    thisis: "Энэ бол Cloud юм шүү.",
    username: "admin",
    password: "Verix123@",
    metaName: "metaCloud",
    imageRootURL: "https://cloud.veritech.mn/app/",
  },
  metaDevCloud: {
    serverUrl: "http://172.169.88.101:8080/erp-services/RestWS/runJson",
    fileAttach: "http://172.169.88.101:8080/erp-services/FileServlet",
    thisis: "Энэ бол DevCloud юм шүү.",
    username: "admin",
    password: "Verix123@",
    metaName: "metaDevCloud",
    imageRootURL: "https://devcloud.veritech.mn/app/",
  },
  metaSkyresort: {
    serverUrl: "http://dev.veritech.mn:8080/erp-services/RestWS/runJson",
    fileAttach: "http://dev.veritech.mn:8080/erp-services/FileServlet",
    thisis: "Энэ бол Sky Resort юм шүү.",
    username: "testuserskyresort",
    password: "123",
    metaName: "metaSkyresort",
    imageRootURL: "https://dev.veritech.mn/",
  },
};
